# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class HomebrewMeshstack < Formula
  meshstack.rb

  desc "Homebrew tap for meshstack cli"
  homepage "https://github.com/afstanton/homebrew-meshstack"
  url "https://github.com/afstanton/homebrew-meshstack/archive/refs/tags/v0.1.14.tar.gz"
  sha256 "29c9e1700aebc08e4a3ea3e333046c7511f95d09d94a978f37f6a4e9c9ffe727"
  license "MIT"

  def install
    brew install --build-from-source ./meshstack.rb
  end
end
